version: '3.8'

services:
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - weathernet
  api:
    container_name: api_open_weather
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_CLIENT: ${MONGO_CLIENT}
      OPEN_WEATHER_API_KEY: ${OPEN_WEATHER_API_KEY}
      OW_URL_5_DIAS: ${OW_URL_5_DIAS}
      OW_URL_GEO: ${OW_URL_GEO}
    networks:
      - weathernet
    restart: always

networks:
  weathernet:
    name: weathernet
    driver: bridge

# volumes:
#     postgres:
#     pgadmin: